#on: [push, pull_request]
on: 
    push:
        branches: '**'
        tags: '' # Restrict to blank tags
    pull_request:
jobs:
 matrix:
    runs-on: ${{ matrix.cfg.os }}
    container: ${{ matrix.cfg.container }}
    defaults:
        run:
            shell: ${{ matrix.cfg.shell }}
    strategy:
        matrix:
            cfg:
            - { os: ubuntu-latest, shell: bash, arch: amd64, runtime: focal, container: 'ros:noetic-perception-focal', desc: 'Ubuntu 20.04 amd64' }
            - { os: ubuntu-latest, shell: bash, arch: amd64, runtime: bionic, container: 'ros:melodic-perception-bionic', desc: 'Ubuntu 18.04 amd64' }
            - { os: ubuntu-latest, shell: bash, arch: amd64, runtime: xenial, container: 'ros:kinetic-perception-xenial', desc: 'Ubuntu 16.04 amd64' }
            - { os: ubuntu-latest, shell: bash, arch: amd64, runtime: trusty, container: 'ros:indigo-perception-trusty', desc: 'Ubuntu 14.04 amd64' }
    name: ${{ matrix.cfg.desc }}
    steps: 
    - uses: actions/checkout@v2
    - run: |
        pwd
        ls
        uname -a && cat /etc/os-release
        apt-get -q update && apt-get -y install lsb-release && lsb_release -a
        source /ros_entrypoint.sh
        mkdir -p ~/catkin_ws/src
        cp -Rf .. ~/catkin_ws/src/
        cd ~/catkin_ws/
        ls src
        catkin_make
