# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lino_msgs/running_time.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class running_time(genpy.Message):
  _md5sum = "fba7101da493706fc2932a90aa6f2991"
  _type = "lino_msgs/running_time"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 time0_pub
float64 time0_sub
float64 time1_pub
float64 time1_sub
float64 time2_pub
float64 time2_sub

"""
  __slots__ = ['time0_pub','time0_sub','time1_pub','time1_sub','time2_pub','time2_sub']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time0_pub,time0_sub,time1_pub,time1_sub,time2_pub,time2_sub

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(running_time, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.time0_pub is None:
        self.time0_pub = 0.
      if self.time0_sub is None:
        self.time0_sub = 0.
      if self.time1_pub is None:
        self.time1_pub = 0.
      if self.time1_sub is None:
        self.time1_sub = 0.
      if self.time2_pub is None:
        self.time2_pub = 0.
      if self.time2_sub is None:
        self.time2_sub = 0.
    else:
      self.time0_pub = 0.
      self.time0_sub = 0.
      self.time1_pub = 0.
      self.time1_sub = 0.
      self.time2_pub = 0.
      self.time2_sub = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.time0_pub, _x.time0_sub, _x.time1_pub, _x.time1_sub, _x.time2_pub, _x.time2_sub))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.time0_pub, _x.time0_sub, _x.time1_pub, _x.time1_sub, _x.time2_pub, _x.time2_sub,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.time0_pub, _x.time0_sub, _x.time1_pub, _x.time1_sub, _x.time2_pub, _x.time2_sub))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.time0_pub, _x.time0_sub, _x.time1_pub, _x.time1_sub, _x.time2_pub, _x.time2_sub,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
