(cl:in-package lino_msgs-msg)
(cl:export '(L1-VAL
          L1
          L2-VAL
          L2
          L3-VAL
          L3
          R1-VAL
          R1
          R2-VAL
          R2
          R3-VAL
          R3
          L_SPEED-VAL
          L_SPEED
          R_SPEED-VAL
          R_SPEED
          L1_PID-VAL
          L1_PID
          L2_PID-VAL
          L2_PID
          L3_PID-VAL
          L3_PID
          R1_PID-VAL
          R1_PID
          R2_PID-VAL
          R2_PID
          R3_PID-VAL
          R3_PID
))